[Config]
MinimumVersion=26

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main,universe

[Output]
Format=disk
Output=testbox
ImageId=testbox
OutputDirectory=mkosi.output
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
RepartOffline=yes

[Build]
ToolsTree=default
ToolsTreeDistribution=debian
ToolsTreeRelease=trixie
