[Content]
Packages=
        linux-image-generic
        systemd
        systemd-sysv
        udev
        grub-pc-bin
        grub-efi-amd64-bin
        btrfs-progs
        dosfstools
        openssh-server
        sudo
        ca-certificates
        netplan.io
