[Content]
Packages=
        linux-image-generic
        initramfs-tools
        systemd
        systemd-sysv
        systemd-boot
        udev
        btrfs-progs
        dosfstools
        openssh-server
        sudo
        ca-certificates
        netplan.io
